/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5653854dc3f2ce0c3c1fa561acd8f9a3)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: "http://localhost:5173";
	ADMIN_EMAILS: "m23568n@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "ADMIN_EMAILS">> {}
}
