/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ddb18a3b487e3589c82f3352904f445d)
interface __BaseEnv_Env {
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	APP_ORIGIN: "https://lokanote.shunzz.com";
	ADMIN_EMAILS: "m23568n@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "ADMIN_EMAILS">> {}
}
